# Generated by Django 4.2.14 on 2024-10-01 17:53

from django.db import migrations, models
import django.db.models.deletion
import reservations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('start_time', reservations.models.TimeChoiceField(verbose_name='start_time')),
                ('end_time', reservations.models.TimeChoiceField(verbose_name='end_time')),
                ('max_people', models.IntegerField(default=20, verbose_name='max_people')),
                ('reserved_people', models.IntegerField(default=0, verbose_name='reserved_people')),
                ('is_max', models.BooleanField(default=False, verbose_name='is_max')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='is_cancelled')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendances.course', verbose_name='course')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('attended', models.BooleanField(default=False, verbose_name='attended')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='is_cancelled')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendances.membership', verbose_name='membership')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.slot', verbose_name='slot')),
            ],
        ),
    ]
