# Generated by Django 4.2.14 on 2024-10-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='max_people',
            field=models.IntegerField(default=25, verbose_name='max_people'),
        ),
    ]
