# Generated by Django 4.2.14 on 2024-11-17 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0006_remove_membership_original_price_and_more'),
        ('reservations', '0002_alter_slot_max_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendances.membership', verbose_name='membership'),
        ),
    ]
