# Generated by Django 4.2.14 on 2025-01-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.FloatField(default=0.0, verbose_name='version')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
            ],
        ),
    ]
