# Generated by Django 4.2.14 on 2026-04-25 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in E.164 format: '+9647501234567'.", regex='^\\+[0-9]{7,15}$')], verbose_name='phone number'),
        ),
    ]
