# Generated by Django 4.2.14 on 2026-09-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stamps',
            field=models.IntegerField(default=0, verbose_name='stamps'),
        ),
    ]
