// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm4ldV71O_GzeUqCPSPJTpewUdYZQSGAo',
    appId: '1:852819913883:android:d854ce91cb5f7111322a3e',
    messagingSenderId: '852819913883',
    projectId: 'wellbee-fitness',
    storageBucket: 'wellbee-fitness.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDMEHhYu69NtjQAmG1PkrGHgz2FImVcCU',
    appId: '1:852819913883:ios:a5a4e157a5001bb7322a3e',
    messagingSenderId: '852819913883',
    projectId: 'wellbee-fitness',
    storageBucket: 'wellbee-fitness.firebasestorage.app',
    iosClientId: '852819913883-ea6gs9io8imka7vf7qndgghm37b37698.apps.googleusercontent.com',
    iosBundleId: 'com.wellbee.fitness',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIJlrgLVgJ_XzbUw0Yv7FvwO489m7gkpE',
    appId: '1:852819913883:web:c4d422f0bca0aabe322a3e',
    messagingSenderId: '852819913883',
    projectId: 'wellbee-fitness',
    authDomain: 'wellbee-fitness.firebaseapp.com',
    storageBucket: 'wellbee-fitness.firebasestorage.app',
    measurementId: 'G-NT731VWRBN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDMEHhYu69NtjQAmG1PkrGHgz2FImVcCU',
    appId: '1:852819913883:ios:a5a4e157a5001bb7322a3e',
    messagingSenderId: '852819913883',
    projectId: 'wellbee-fitness',
    storageBucket: 'wellbee-fitness.firebasestorage.app',
    iosBundleId: 'com.wellbee.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIJlrgLVgJ_XzbUw0Yv7FvwO489m7gkpE',
    appId: '1:852819913883:web:105f2b66fbb8cfa2322a3e',
    messagingSenderId: '852819913883',
    projectId: 'wellbee-fitness',
    authDomain: 'wellbee-fitness.firebaseapp.com',
    storageBucket: 'wellbee-fitness.firebasestorage.app',
    measurementId: 'G-TMG11KKY12',
  );

}