# Generated by Django 4.2.14 on 2024-11-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='response20',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='response21',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='response22',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='response23',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='response24',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='response25',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='response26',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='response27',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='score20',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='score21',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='score22',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='score23',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='score24',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='score25',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='score26',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='score27',
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='response0',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='response0'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='response1',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='response1'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='response10',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='response10'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='response11',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='response11'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='response12',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='response12'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='response13',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='response13'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='response14',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='response14'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='response15',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='response15'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='response16',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='response16'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='response17',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='response17'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='response18',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='response18'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='response19',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='response19'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='response2',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='response2'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='response3',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='response3'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='response4',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='response4'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='response5',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='response5'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='response6',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='response6'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='response7',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='response7'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='response8',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='response8'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='response9',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], verbose_name='response9'),
        ),
    ]
