# Generated by Django 4.2.14 on 2024-10-01 17:53

import attendances.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('Not specified', 'Not specified')], max_length=20, verbose_name='gender')),
                ('date_of_birth', models.DateField(verbose_name='date_of_birth')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('any_comment', models.CharField(blank=True, max_length=150, null=True, verbose_name='any_comment')),
                ('reason', models.CharField(blank=True, max_length=150, null=True, verbose_name='reason')),
                ('goal', models.CharField(blank=True, max_length=150, null=True, verbose_name='goal')),
                ('last_survey_date', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('Yoga', 'Yoga'), ('Kids Yoga', 'Kids Yoga'), ('Dance', 'Dance'), ('Kids Dance', 'Kids Dance'), ('Karate', 'Karate'), ('Kids Karate', 'Kids Karate'), ('Kids Taiso', 'Kids Taiso'), ('Music', 'Music'), ('Kids Music', 'Kids Music'), ('Pilates', 'Pilates'), ('Family Pilates', 'Family Pilates'), ('Family Yoga', 'Family Yoga')], default='Yoga', max_length=20, verbose_name='course_name')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.IntegerField(choices=[(10, '10$'), (20, '20$'), (30, '30$'), (40, '40$'), (50, '50$'), (60, '60$'), (70, '70$'), (80, '80$'), (90, '90$'), (100, '100$'), (110, '110$'), (120, '120$'), (130, '130$'), (140, '140$'), (150, '150$')], verbose_name='original_price')),
                ('times_per_week', models.IntegerField(choices=[(1, '1 time'), (2, '2 times')], verbose_name='times_per_week')),
                ('num_person', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='num_person')),
                ('duration', models.IntegerField(choices=[(1, '1 month'), (3, '3 months'), (6, '6 months'), (12, '1 year')], verbose_name='duration')),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True, verbose_name='is_approved')),
                ('total_price', models.IntegerField(null=True, verbose_name='total_price')),
                ('discount_rate', models.FloatField(choices=[(1.0, 'No Discount'), (0.95, '5% OFF'), (0.9, '10% OFF'), (0.85, '15% OFF'), (0.8, '20% OFF'), (0.75, '25% OFF'), (0.7, '30% OFF'), (0.65, '35% OFF'), (0.6, '40% OFF'), (0.55, '45% OFF'), (0.5, '50% OFF'), (0.45, '55% OFF'), (0.4, '60% OFF')], verbose_name='discount_rate')),
                ('discounted_total_price', models.IntegerField(null=True, verbose_name='discounted_total_price')),
                ('max_join_times', models.IntegerField(null=True, verbose_name='max_times_join')),
                ('requested_join_times', models.IntegerField(default=0, null=True, verbose_name='requested_join_times')),
                ('already_join_times', models.IntegerField(default=0, null=True, verbose_name='already_join_times')),
                ('expire_day', models.DateField(default=attendances.models.get_today, verbose_name='expire_day')),
                ('is_expired', models.BooleanField(default=False, verbose_name='is_expired')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendances.attendee', verbose_name='attendee')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendances.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_state', models.CharField(blank=True, max_length=300, null=True, verbose_name='reason')),
                ('physical_state', models.CharField(blank=True, max_length=300, null=True, verbose_name='goal')),
                ('any_comment', models.CharField(blank=True, max_length=300, null=True, verbose_name='any_comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendances.attendee', verbose_name='attendee')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_person', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='num_person')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='checked_by')),
            ],
        ),
    ]
