# Generated by Django 4.2.14 on 2024-10-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('Yoga', 'Yoga'), ('Kids Yoga', 'Kids Yoga'), ('Zomba', 'Zomba'), ('Dance', 'Dance'), ('Kids Dance', 'Kids Dance'), ('Karate', 'Karate'), ('Kids Karate', 'Kids Karate'), ('Kids Taiso', 'Kids Taiso'), ('Music', 'Music'), ('Kids Music', 'Kids Music'), ('Pilates', 'Pilates'), ('Family Pilates', 'Family Pilates'), ('Family Yoga', 'Family Yoga')], default='Yoga', max_length=20, verbose_name='course_name'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='emotion_state',
            field=models.CharField(default=3, max_length=300, verbose_name='reason'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interview',
            name='physical_state',
            field=models.CharField(default=3, max_length=300, verbose_name='goal'),
            preserve_default=False,
        ),
    ]
