# Generated by Django 4.2.14 on 2024-11-11 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendances', '0004_alter_course_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='minus',
            field=models.IntegerField(choices=[(0, '0'), (10, '10'), (20, '20'), (30, '30'), (40, '40'), (50, '50'), (60, '60'), (70, '70'), (80, '80'), (90, '90'), (100, '100')], default=0, verbose_name='minus'),
        ),
        migrations.AddField(
            model_name='membership',
            name='start_day',
            field=models.DateField(null=True, verbose_name='start_day'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('Yoga', 'Yoga'), ('Kids Yoga(A)', 'Kids Yoga(A)'), ('Zumba', 'Zumba'), ('Dance', 'Dance'), ('Kids Dance', 'Kids Dance'), ('Karate', 'Karate'), ('Kids Karate', 'Kids Karate'), ('Kids Taiso(A)', 'Kids Taiso(A)'), ('Music', 'Music'), ('Kids Music', 'Kids Music'), ('Pilates', 'Pilates'), ('Family Pilates', 'Family Pilates'), ('Family Yoga', 'Family Yoga'), ('Kids Taiso(B)', 'Kids Taiso(B)'), ('Kids Yoga KG', 'Kids Yoga KG'), ('Kids Yoga(B)', 'Kids Yoga(B)'), ('Private Yoga(Studio)', 'Private Yoga(Studio)'), ('Private Yoga(Home)', 'Private Yoga(Home)'), ('Private Pilates(Studio)', 'Private Pilates(Studio)'), ('Private Pilates(Home)', 'Private Pilates(Home)')], default='Yoga', max_length=25, verbose_name='course_name'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='attendee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendances.attendee', verbose_name='attendee'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='duration',
            field=models.IntegerField(choices=[(1, '1 month'), (2, '2 months'), (3, '3 months'), (4, '4 months'), (5, '5 month'), (6, '6 months'), (7, '7 months'), (8, '8 months'), (9, '9 months'), (10, '10 months'), (11, '11 months'), (12, '1 year'), (13, '13 months'), (14, '14 months'), (15, '15 months'), (16, '16 months'), (17, '17 months'), (18, '1 year 6 months'), (19, '19 months')], verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='max_join_times',
            field=models.IntegerField(null=True, verbose_name='max_join_times'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
