# Generated by Django 4.2.14 on 2024-11-17 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_slot_max_people'),
        ('attendances', '0005_membership_minus_membership_start_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='original_price',
        ),
        migrations.AlterField(
            model_name='checkin',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation', verbose_name='reservation'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='duration',
            field=models.IntegerField(choices=[(1, '1 month'), (3, '3 months'), (6, '6 months'), (12, '1 year')], verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='minus',
            field=models.IntegerField(default=0, verbose_name='minus'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='num_person',
            field=models.IntegerField(default=1, verbose_name='num_person'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='times_per_week',
            field=models.IntegerField(default=1, verbose_name='times_per_week'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='total_price',
            field=models.IntegerField(default=100, verbose_name='total_price'),
        ),
    ]
