# Generated by Django 4.2.14 on 2024-11-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0006_remove_membership_original_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='total_price',
            field=models.IntegerField(verbose_name='total_price'),
        ),
    ]
