# Generated by Django 4.2.14 on 2024-11-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0007_alter_membership_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='offer',
            field=models.IntegerField(blank=True, choices=[(0, 'No offer'), (48, '1 month free(3 months)'), (42, '1 month free(6 months)'), (30, '1 month free(12 months)'), (45, '1 month free(Kids 3 months)')], null=True, verbose_name='offer'),
        ),
    ]
