# Generated by Django 4.2.14 on 2024-11-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0008_membership_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='is_private'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('Yoga', 'Yoga'), ('Zumba', 'Zumba'), ('Pilates', 'Pilates'), ('Kids Yoga(A)', 'Kids Yoga(A)'), ('Kids Yoga(B)', 'Kids Yoga(B)'), ('Kids Yoga KG', 'Kids Yoga KG'), ('Kids Zumba', 'Kids Zumba'), ('Kids Karate', 'Kids Karate'), ('Kids Gym(A)', 'Kids Gym(A)'), ('Kids Gym(B)', 'Kids Gym(B)'), ('P_Yoga@Studio', 'P_Yoga@Studio'), ('P_Yoga@Home', 'P_Yoga@Home'), ('P_Pilates@Studio', 'P_Pilates@Studio'), ('P_Pilates@Home', 'P_Pilates@Home')], default='Yoga', max_length=25, verbose_name='course_name'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='duration',
            field=models.IntegerField(choices=[(1, '1 month'), (2, '2 months'), (3, '3 months'), (6, '6 months'), (12, '1 year')], verbose_name='duration'),
        ),
    ]
