# Generated by Django 4.2.14 on 2024-11-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0009_course_is_private_alter_course_course_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='times_per_week',
        ),
        migrations.AddField(
            model_name='membership',
            name='times',
            field=models.IntegerField(default=1, verbose_name='times'),
        ),
    ]
