# Generated by Django 4.2.14 on 2024-11-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0010_remove_membership_times_per_week_membership_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='offer',
            field=models.IntegerField(blank=True, choices=[(0, 'No offer'), (48, '1 month free(3 months)'), (42, '1 month free(6 months)'), (30, '1 month free(12 months)'), (45, '1 month free(Kids 3 months)')], default=0, null=True, verbose_name='offer'),
        ),
    ]
