# Generated by Django 4.2.14 on 2024-12-26 01:36

import attendances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0011_alter_membership_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='last_check_in',
            field=models.DateField(default=attendances.models.get_today, verbose_name='last_check_in'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('Yoga', 'Yoga'), ('Zumba', 'Zumba'), ('Pilates', 'Pilates'), ('Kids Yoga(A)', 'Kids Yoga(A)'), ('Kids Yoga(B)', 'Kids Yoga(B)'), ('Kids Yoga KG', 'Kids Yoga KG'), ('Kids Zumba', 'Kids Zumba'), ('Kids Karate', 'Kids Karate'), ('Kids Gym(A)', 'Kids Gym(A)'), ('Kids Gym(B)', 'Kids Gym(B)'), ('Private Yoga@Studio', 'Private Yoga@Studio'), ('Private Yoga@Home', 'Private Yoga@Home'), ('Private Pilates@Studio', 'Private Pilates@Studio'), ('Private Pilates@Home', 'Private Pilates@Home')], default='Yoga', max_length=25, verbose_name='course_name'),
        ),
    ]
