# Generated by Django 4.2.14 on 2025-12-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0012_membership_last_check_in_alter_course_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='is_open'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='Yoga', max_length=25, verbose_name='course_name'),
        ),
    ]
