# Generated by Django 4.2.14 on 2025-12-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0013_course_is_open_alter_course_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='asset_image_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='asset_image_path'),
        ),
    ]
