# Generated by Django 4.2.14 on 2026-01-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0014_course_asset_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='course_image'),
        ),
    ]
