# Generated by Django 4.2.14 on 2026-01-05 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0015_course_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='asset_image_path',
        ),
    ]
