# Generated by Django 4.2.14 on 2026-02-09 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendances', '0016_remove_course_asset_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDaysSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before_expire', models.IntegerField(unique=True, verbose_name='days_before_expire')),
                ('message', models.TextField(verbose_name='message')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NotificationDaysSetting',
                'verbose_name_plural': 'NotificationDaysSettings',
                'ordering': ['days_before_expire'],
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('is_read', models.BooleanField(default=False, verbose_name='is_read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read_at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserMessage',
                'verbose_name_plural': 'UserMessages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='attendances_user_id_d8d673_idx'), models.Index(fields=['user', '-created_at'], name='attendances_user_id_800596_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserFCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='fcm_token')),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20, verbose_name='device_type')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserFCMToken',
                'verbose_name_plural': 'UserFCMTokens',
                'unique_together': {('user', 'token')},
            },
        ),
    ]
